# Generated by Django 6.0.5 on 2026-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tramite', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
