# Generated by Django 6.0.5 on 2026-06-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_ciudadano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('reprogramado', 'Reprogramado')], default='pendiente', max_length=20)),
                ('email_notificacion', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.ciudadano')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.oficina')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.tramite')),
            ],
        ),
    ]
