# Generated by Django 6.0.5 on 2026-06-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.turno')),
            ],
        ),
    ]
